#!/bin/bash

#
# gofvimdiff
#
# This script works with gofci; it diffs the current working version of the
# file against the most recently committed version using vimdiff.
#

TEMPFILENAME=/var/tmp/gofvimdiff.temp

FILENAME="$1"
if [[ -z $FILENAME ]] ; then echo please supply filename ; exit ; fi
export GIT_DIR="$FILENAME.git"

# if repo doesn't exist, bail
if [[ ! -e $GIT_DIR ]] ; then
    echo "$GIT_DIR" does not exist.  exiting.
    exit
fi

git show master:"$FILENAME" > $TEMPFILENAME
vimdiff "$FILENAME" $TEMPFILENAME
rm $TEMPFILENAME

# the other option is to use the other scripts:
# gofcat "$FILENAME" > $TEMPFILENAME && vimdiff "$FILENAME" $TEMPFILENAME && rm $TEMPFILENAME

# vim:sw=4:et:ai:ic
